[programs.localnet]
lockup = "AhBzgeqkGbYqhuEgFBxZstACQnk4ph11ydhiS5msqLTF"
registry = "BUzd3qEn2E4BhGjPVF3KgdtdNDwA6KcZaCKVZZVk13fR"
registry_realizor = "GUr5Vat45m3H7JHm1F6FYzytGwATbqNfUHQa935332SU"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
# cluster = "https://rpc-mainnet-fork.dappio.xyz"
# cluster = "https://rpc-mainnet-fork.epochs.studio"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
